### ISSUE TITLE
Defect: Cannot Save Attachment Without Revision ID

### ISSUE THREAD

**Issue by dlandis** [cloudant/java-cloudant#186]
Using the latest version, it is not possible to save a new attachment with an id.

Here is the stack trace:

```
2016-01-20T16:47:34.92-0800 [App/0]      OUT java.lang.NullPointerException
2016-01-20T16:47:34.92-0800 [App/0]      OUT 	at com.cloudant.client.internal.URIBaseMethods.path(URIBaseMethods.java:37)
2016-01-20T16:47:34.92-0800 [App/0]      OUT 	at com.cloudant.client.internal.DatabaseURIHelper.revId(DatabaseURIHelper.java:179)
2016-01-20T16:47:34.92-0800 [App/0]      OUT 	at com.cloudant.client.internal.DatabaseURIHelper.attachmentUri(DatabaseURIHelper.java:160)
2016-01-20T16:47:34.92-0800 [App/0]      OUT 	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.saveAttachment(CouchDatabaseBase.java:342)
2016-01-20T16:47:34.92-0800 [App/0]      OUT 	at com.cloudant.client.api.Database.saveAttachment(Database.java:960)
```

The `saveAttachment` method was called with a `null` value for the `docRev` argument, which is correct according to the JavaDoc:

    @param docRev The document revision to save the attachment under, or {@code null} when saving to a new document.

**Comment by dlandis** [comment]
ping @emlaver 

Also noticed some other issues in the APIs for example:

     * @param docId       The document id to save the attachment under, or {@code null} to save
     *                    under a new document.

And then the first line of the method is:

    assertNotEmpty(docId, "docId");

**Comment by dlandis** [comment]
see pull request #187

**Comment by dlandis** [comment]
Note, a temporary workaround for this issue is to use an empty string instead of null for the `docRev` argument.
