### ISSUE TITLE
Failure when removing design documents (for indexes)

### ISSUE THREAD

**Issue by stephen-kruger** [cloudant/java-cloudant#239]
Cloudant 2.4.1
Using a previously suggested method to list design documents : 
```java
List<String> designDocIds = database.getAllDocsRequestBuilder()
                                    .startKey("_design/")
                                    .endKey("_design0")
                                    .build()
                                    .getResponse()
                                    .getDocIds();
```

I then remove each one using : 
`DesignDocumentManager ddm = database.getDesignDocumentManager();
ddm.remove(designDocId);`

This works fine for views etc, but when it hits a DD for Indexes, I get this error : 
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 133
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at com.cloudant.client.org.lightcouch.internal.CouchDbUtil.getResponse(CouchDbUtil.java:211)
	at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:329)
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.find(CouchDatabaseBase.java:88)
	at com.cloudant.client.api.Database.find(Database.java:536)
	at com.cloudant.client.api.DesignDocumentManager.remove(DesignDocumentManager.java:154)```

**Comment by ricellis** [comment]
@stephen-kruger thanks for reporting this. When deleting a design document without providing a revision the `DesignDocumentManager` performs a `GET` first to discover the latest revision to delete. It appears that the deserialization into a `DesignDocument` at this point is failing.

Q1: Do you see the same exception if you do a `database.getDesignDocumentManager().get(designDocId)`?

Q2: I have not been able to reproduce this, do you have an example of a design document that fails to delete?

If a revision is specified the `DesignDocumentManager` will not attempt to deserialize the design document, so it might be possible to workaround while we investigate by specifying the revision that you want to delete (assuming that the design document is unlikely to be updated at the same time). So you could alter your all docs request to use `getIdsAndRevs()` instead of `getDocIds()` for example:
```java
for (Map.Entry<String, String> docInfo : database.getAllDocsRequestBuilder()
                                                 .startKey("_design/")
                                                 .endKey("_design0")
                                                 .build()
                                                 .getResponse()
                                                 .getIdsAndRevs()
                                                 .entrySet()) {
    database.getDesignDocumentManager().remove(docInfo.getKey(), docInfo.getValue());
}
```
As an aside this will be significantly faster as it halves the number of round trips your code needs to make to the server because it won't need to fetch the revision information (again assuming that the design document is not likely to be updated between your all docs request and the delete).

**Comment by stephen-kruger** [comment]
Hi,

Here is the method I call to remove all design docs, but leave the "data" in place, used for migrating views etc. I added a printStackTrace() to illustrate the error, and include the trace and design doc below.
```java
public void removeDesignDocs(Database database) {
		try {
			List<String> designDocIds = database.getAllDocsRequestBuilder()
					.startKey("_design/")
					.endKey("_design0")
					.includeDocs(true)
					.build()
					.getResponse()
					.getDocIds();
			DesignDocumentManager ddm = database.getDesignDocumentManager();
			for (String id : designDocIds) {
				try {
					log.info("Removing design doc {}",id);
					ddm.remove(id);
				}
				catch (Throwable t) {
					t.printStackTrace();
					try {
						JsonObject jo = database.find(JsonObject.class, id);
						log.info("Removing index {}",id);
						database.remove(id, jo.get("_rev").getAsString());
					}
					catch (Throwable t2) {
						log.error("Problem removing index",t2);
					}
				}
			}
		}
		catch (Throwable t) {
			log.error("Problem removing design docs from db",t);
		}
	}
```
The stack trace : 
```
11-04-16 22:06:43 INFO  WsClient(217): Removing design doc _design/tenantUidModifiedAsc
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 132
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at com.cloudant.client.org.lightcouch.internal.CouchDbUtil.getResponse(CouchDbUtil.java:211)
	at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:329)
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.find(CouchDatabaseBase.java:88)
	at com.cloudant.client.api.Database.find(Database.java:536)
	at com.cloudant.client.api.DesignDocumentManager.remove(DesignDocumentManager.java:154)
	at com.xxx.sw.project.WsClient.removeDesignDocs(WsClient.java:218)
	at com.xxx.sw.project.WsClient.updateDesignDoc(WsClient.java:281)
	at com.xxx.sw.project.WsClient.upgrade(WsClient.java:239)
	at com.xxx.sw.project.WsClient.connect(WsClient.java:134)
	at com.xxx.sw.project.WsClient.<init>(WsClient.java:86)
	at com.xxx.sw.project.WsClient.getInstance(WsClient.java:92)
	at com.xxx.sw.project.BaseTest.setUp(BaseTest.java:36)
	at com.xxx.sw.project.TestWsClientNoPopulation.setUp(TestWsClientNoPopulation.java:53)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 132
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:821)
	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:358)
	at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:346)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	... 34 more
```

The _design/tenantUidModifiedAsc. Oddly I never set the reduce function - it puts that in by default for some reason. : 
```javascript
{
  "_id": "_design/tenantUidModifiedAsc",
  "_rev": "23-f8817c7aecb1789198df53cfe878ff95",
  "language": "query",
  "views": {
    "cardIndex": {
      "map": {
        "fields": {
          "owner.tenantUid": "asc",
          "modified": "asc"
        }
      },
      "reduce": "_count",
      "options": {
        "def": {
          "fields": [
            {
              "owner.tenantUid": "asc"
            },
            {
              "modified": "asc"
            }
          ]
        }
      }
    }
  }
}
```

Let me know if you need anything else.

**Comment by stephen-kruger** [comment]
I changed my code to use your method, and no longer get the exception.
```java
	public void removeDesignDocs(Database database) {
		try {
			for (Map.Entry<String, String> docInfo : database.getAllDocsRequestBuilder()
					.startKey("_design/")
					.endKey("_design0")
					.build()
					.getResponse()
					.getIdsAndRevs()
					.entrySet()) {
				try {
					log.info("Removing design doc {}",docInfo.getKey());
					database.getDesignDocumentManager().remove(docInfo.getKey(), docInfo.getValue());
				}
				catch (Throwable t) {
					log.error("Problem removing index {} {}",docInfo.getKey(),docInfo.getValue(),t);
				}
			}
		}
		catch (Throwable t) {
			log.error("Problem removing design docs from db",t);
		}
	}
```

I think this rules out an issue in my design doc.

**Comment by ricellis** [comment]
@stephen-kruger thanks for the extra information - with that example design doc I was able to see the location of the deserialization problem.

The issue is that the java-cloudant `DesignDocument` class is expecting the `views.cardindex.map` property to be a `String` map function (e.g. the normal javascript view style like `"function(doc) { if (doc.foo) { emit(doc._id, doc.foo); } }"`. For query design documents from creating indexes the map property is a JSON object.

So I think there are two fixes that should come out of this issue:

1. We will need to improve the deserialization to handle these other cases in design documents.
2. We should improve the `remove` logic so that it doesn't `GET` and deserialize a design document just to get the revision information. A `HEAD` request would improve the performance.
