### ISSUE TITLE
Recovery from broken continous change stream?

### ISSUE THREAD

**Issue by icha024** [cloudant/java-cloudant#245]
Question: What is the recommended way to recover from a broken continous change stream?

I am working on a little app that listens to all DB change, then augment it with extra data and save it in a separate DB. Here is the problem, when there are any network outage, the while(changes.hasNext()) line throws an error when the stream is broken and fail to recover when the network connection is resumed. What is the recommended way to handle this scenario and make sure it continues listening for changes?

```
com.cloudant.client.org.lightcouch.CouchDbException: Error reading continuous stream.
	at com.cloudant.client.org.lightcouch.Changes.readNextRow(Changes.java:197) ~[cloudant-client-2.4.2.m1.jar:na]
	at com.cloudant.client.org.lightcouch.Changes.hasNext(Changes.java:112) ~[cloudant-client-2.4.2.m1.jar:na]
	at com.cloudant.client.api.Changes.hasNext(Changes.java:93) ~[cloudant-client-2.4.2.m1.jar:na]

Caused by: java.io.IOException: Stream closed
	at java.io.BufferedReader.ensureOpen(BufferedReader.java:122) ~[na:1.8.0_66]
	at java.io.BufferedReader.readLine(BufferedReader.java:317) ~[na:1.8.0_66]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[na:1.8.0_66]
	at com.cloudant.client.org.lightcouch.Changes.readNextRow(Changes.java:184) ~[cloudant-client-2.4.2.m1.jar:na]
	... 11 common frames omitted
```

**Comment by ricellis** [comment]
You can get the sequence ID from each changes row you get:
```java
ChangesResult.Row row = changes.next();
String seq = row.getSeq();
```
Then you could restart the feed from the appropriate place using that ID:
`database.changes().since(seq).continuousChanges();`

As per the [Cloudant documentation](https://docs.cloudant.com/database.html#get-changes) it is worth noting that you might receive the same changes more than once.

**Comment by icha024** [comment]
Thanks!
