### ISSUE TITLE
CookieInterceptor -  java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jrodri14** [cloudant/java-cloudant#287]
We have our application running on IBM Bluemix Containers and after several hours (4-8hrs) we see a lot of StringIndexOutOfBoundsException.

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
CloudantClient 2.5.1

- Java version (including vendor and platform).
java 1.7

- If you're using the optional okhttp dependency.
Not sure.

- A small code sample that demonstrates the issue.

[8/19/16 1:11:58:961 UTC] 000000a0 .cloud.liberty.archaius_cloudant.CloudantConfigurationSource E An exception occurred while reading from [CloudantDB:cosmos-svt-cluster_ecmconfig,cosmosci]:
java.lang.StringIndexOutOfBoundsException
    at java.lang.String.substring(String.java:1360)
    at com.cloudant.http.interceptors.CookieInterceptor.extractCookieFromHeaderValue(CookieInterceptor.java:232)
    at com.cloudant.http.interceptors.CookieInterceptor.interceptResponse(CookieInterceptor.java:99)
    at com.cloudant.http.HttpConnection.execute(HttpConnection.java:357)
    at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:475)
    at com.cloudant.client.api.CloudantClient.executeRequest(CloudantClient.java:335)
    at com.cloudant.client.internal.views.ViewRequester.executeRequestWithResponseAsJson(ViewRequester.java:34)
    at com.cloudant.client.internal.views.ViewRequester.getResponseAsJson(ViewRequester.java:28)
    at com.cloudant.client.internal.views.ViewRequestImpl.getResponse(ViewRequestImpl.java:34)
    at com.cloudant.client.internal.views.AllDocsRequestResponse.getResponse(AllDocsRequestResponse.java:44)
    at com.ibm.ecm.cloud.liberty.archaius_cloudant.CloudantConfigurationSource.loadAllProperties(CloudantConfigurationSource.java:82)
    at com.ibm.ecm.cloud.liberty.archaius_cloudant.CloudantConfigurationSource.poll(CloudantConfigurationSource.java:120)
    at com.netflix.config.AbstractPollingScheduler$1.run(AbstractPollingScheduler.java:163)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:309)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1143)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:618)
    at java.lang.Thread.run(Thread.java:785)

**Comment by ricellis** [comment]
At https://github.com/cloudant/java-cloudant/blob/master/cloudant-http/src/main/java/com/cloudant/http/interceptors/CookieInterceptor.java#L249

We should be more careful handling the cookie string, for example checking that `cookieHeaderValue.indexOf(";")` is > 0 before attempting to get the sub-string.

**Comment by jrodri14** [comment]
Thanks Richard!

**Comment by jrodri14** [comment]
When would we expect it to be available in the maven repository ?

**Comment by ricellis** [comment]
The repository at https://oss.sonatype.org/content/repositories/snapshots has `com.cloudant:cloudant-client:2.5.2-SNAPSHOT` artifacts already which could be used for testing. We will do a new release to maven central quite soon, I think we just need to get one more issue into the 2.6.0 milestone first.
