### ISSUE TITLE
Is OkHttp no longer optional?

### ISSUE THREAD

**Issue by stephen-kruger** [cloudant/java-cloudant#294]
Upgrading to the 2.6.0 version now gives he following error : 

java.lang.NoClassDefFoundError: com.squareup.okhttp.Authenticator
	at com.cloudant.client.org.lightcouch.CouchDbClient.<init>(CouchDbClient.java:95)
	at com.cloudant.client.org.lightcouch.CouchDbClient.<init>(CouchDbClient.java:140)
	at com.cloudant.client.api.CloudantClient.<init>(CloudantClient.java:138)
	at com.cloudant.client.api.ClientBuilder.build(ClientBuilder.java:330)
...
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.Authenticator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:607)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:797)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:771)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:325)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:752)
	... 23 more

- CloudantClient (java-cloudant) version(s) that are affected by this issue. : 2.6.0
- Java version (including vendor and platform). IBM JDK 1.8
- If you're using the optional okhttp dependency. No

**Comment by ricellis** [comment]
It is still intended to be optional I'll look into it.

**Comment by ricellis** [comment]
The problem is I used a static inner class that implemented an okhttp interface in the class that performs the check for whether okhttp is available. That causes the JVM to try and load the interface, but it is too early (i.e. before we've done the check for whether okhttp is available).
I will get a fix in.

**Comment by stephen-kruger** [comment]
Thanks for the quick resolution - do you have a timeline for the 2.6.1 release?

**Comment by ricellis** [comment]
I have released 2.6.1 since this was a blocking issue for using 2.6.0 without okhttp.

**Comment by stephen-kruger** [comment]
Using the 2.6.1 client with no OkHttp dep declared, I'm getting a similar stack trace  
java.lang.NoClassDefFoundError: com.squareup.okhttp.Authenticator
	at com.cloudant.client.org.lightcouch.CouchDbClient.<init>(CouchDbClient.java:95)
	at com.cloudant.client.org.lightcouch.CouchDbClient.<init>(CouchDbClient.java:140)
	at com.cloudant.client.api.CloudantClient.<init>(CloudantClient.java:138)
	at com.cloudant.client.api.ClientBuilder.build(ClientBuilder.java:344)
...
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.Authenticator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:607)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:797)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:771)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:325)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:752)
	... 25 more

**Comment by stephen-kruger** [comment]
I think the imports in your factory class are enough to cause this - the classloader won't be able to load the factory class to even get into the static check  
OkHttpClientHttpUrlConnectionFactory.java
> import com.cloudant.http.internal.DefaultHttpUrlConnectionFactory;
> import com.squareup.okhttp.ConnectionSpec;
> import com.squareup.okhttp.Credentials;
> import com.squareup.okhttp.OkHttpClient;
> import com.squareup.okhttp.OkUrlFactory;

**Comment by ricellis** [comment]
The imports should have no consequence once compiled into the byte code where methods are invoked by their FQN. We've been using (at least some of) the [imports in this class since 2.0.0](https://github.com/cloudant/java-cloudant/blob/2.0.0/src/main/java/com/cloudant/http/internal/ok/OkHttpClientHttpUrlConnectionFactory.java#L18) and it has worked.

I've found the issue with my test environment that snuck okhttp onto the classpath and made it look like my 2.6.1 fix was working so I'll start digging into it again.

**Comment by ricellis** [comment]
So the problem appears to be the line that calls the okhttp `client.setAuthenticator(Authenticator)` method. The method signature for that set references the `Authenticator` so unless we call it reflectively there is no way to include it in the class. We managed to get away with it for other methods because they either type erased to `Object` at runtime (e.g. the array of connection specs) or they were fields or new instances of types, but no other method signatures directly referenced an okhttp type.

I'll work on a fix, try to come up with a better test and then a 2.6.2 release. Sorry for the inconvenience.

**Comment by ricellis** [comment]
@stephen-kruger I've released 2.6.2 and tested it in isolation as well as testing the fix itself two different ways so hopefully I've really managed to fix it this time! Sorry again for the inconvenience.
