### ISSUE TITLE
java.lang.NoClassDefFoundError: com.squareup.okhttp.Authenticator

### ISSUE THREAD

**Issue by jrodri14** [cloudant/java-cloudant#299]
I see that okhttp is optional and we're seeing **Caused by: java.lang.NoClassDefFoundError: com.squareup.okhttp.Authenticator**

Please include the following information in your ticket.

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
  2.6.0
- Java version (including vendor and platform).
      1.7 
- If you're using the optional okhttp dependency.
     **Not using okhttp**
- A small code sample that demonstrates the issue.

Caused by: java.lang.NoClassDefFoundError: com.ibm.ecm.box.auth.helper.GafHelper (initialization failure)
        at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:87)
        at com.ibm.ecm.box.auth.tai.GalaxyTAI.processGafToken(GalaxyTAI.java:76)
        at com.ibm.ecm.box.auth.tai.GalaxyTAI.negotiateValidateandEstablishTrust(GalaxyTAI.java:392)
        at com.ibm.ws.webcontainer.security.internal.TAIAuthenticator.authenticate(TAIAuthenticator.java:110)
        at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorProxy.handleTAI(WebProviderAuthenticatorProxy.java:250)
        at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorProxy.authenticate(WebProviderAuthenticatorProxy.java:109)
        at com.ibm.ws.webcontainer.security.WebAuthenticatorProxy.authenticate(WebAuthenticatorProxy.java:69)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.authenticateRequest(WebAppSecurityCollaboratorImpl.java:950)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.determineWebReply(WebAppSecurityCollaboratorImpl.java:770)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.performSecurityChecks(WebAppSecurityCollaboratorImpl.java:600)
        at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.preInvoke(WebAppSecurityCollaboratorImpl.java:524)
        at com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper.preInvokeCollaborators(CollaboratorHelper.java:457)
        at com.ibm.ws.webcontainer.osgi.collaborator.CollaboratorHelperImpl.preInvokeCollaborators(CollaboratorHelperImpl.java:267)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1124)
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4867)
        ... 18 more
Caused by: java.lang.NoClassDefFoundError: com.squareup.okhttp.Authenticator
        at com.cloudant.client.org.lightcouch.CouchDbClient.<init>(CouchDbClient.java:95)
        at com.cloudant.client.org.lightcouch.CouchDbClient.<init>(CouchDbClient.java:140)
        at com.cloudant.client.api.CloudantClient.<init>(CloudantClient.java:138)
        at com.cloudant.client.api.ClientBuilder.build(ClientBuilder.java:330)
        at com.ibm.ecm.box.auth.helper.GafHelper.tryAcquireDatabase(GafHelper.java:120)
        at com.ibm.ecm.box.auth.helper.GafHelper.getCloudantInfo(GafHelper.java:82)
        at com.ibm.ecm.box.auth.helper.GafHelper.DBPrep(GafHelper.java:164)
        at com.ibm.ecm.box.auth.helper.GafHelper.<clinit>(GafHelper.java:209)
        at com.ibm.ecm.box.auth.tai.GalaxyTAI.processGafToken(GalaxyTAI.java:76)

**Comment by jrodri14** [comment]
Ah i see this is a duplicate of https://github.com/cloudant/java-cloudant/issues/294

**Comment by rhyshort** [comment]
Thanks for spotting its a duplicate, closing.
