### ISSUE TITLE
How to register custom converters? 

### ISSUE THREAD

**Issue by schmitzhermes** [cloudant/java-cloudant#357]
Hey guys,
we are facing an issue with `java-cloudant`, particularly regarding Java's new Date/Time libraries. We save a `ZonedDateTime` in the database (which works fine), but when we want to read it from the database (i.e. deserialize the JSON object), we are facing the following exception:
```
org.glassfish.jersey.server.internal.process.MappableException: java.lang.RuntimeException: Failed to invoke java.time.ZoneId() with no args
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.mapTargetToRuntimeEx(AbstractJavaResourceMethodDispatcher.java:179)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.access$200(AbstractJavaResourceMethodDispatcher.java:72)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:149)
	[...]
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to invoke java.time.ZoneId() with no args
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:111)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at com.cloudant.client.org.lightcouch.internal.CouchDbUtil.getResponse(CouchDbUtil.java:229)
	at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:334)
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.find(CouchDatabaseBase.java:85)
	at com.cloudant.client.api.Database.find(Database.java:527)
	at com.ibm.ega.immunization.data.cloudant.CloudantImmunizationDB.getImmunization(CloudantImmunizationDB.java:124)
	at com.ibm.ega.immunization.api.facade.ImmunizationService.getImmunization(ImmunizationService.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	[...]
```

Apparently deserializing `ZonedDateTime` from ISO8601 into a Java object seems to be the issue.

In our team, this raised the question: "How can we register custom GSON converters to avoid this issue?". I digged a little into your source code and found [this line](https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/main/java/com/cloudant/client/org/lightcouch/CouchDbClient.java#L92). It seems that there is no possibility to register custom converters (apart from those you guys already register).

Two questions:
a) Am I doing something wrong deserializing the `ZonedDateTime`? 
b) Is it really desired behaviour that one can not register custom converters? 

If there is any interest, I'd be happy to provide a PR that helps solving the issue. 

Please include the following information in your ticket.
- CloudantClient (java-cloudant) version(s) that are affected by this issue: 2.8.0
- Java version (including vendor and platform): OpenJDK 1.8, macOS
- If you're using the optional okhttp dependency: No

Thanks in advance.

**Comment by ricellis** [comment]
The line you point out configures an initial value, but we later call a setter to set it with a provided builder if one was supplied.

Use the [`ClientBuilder.gsonBuilder()`](http://static.javadoc.io/com.cloudant/cloudant-client/2.9.0/com/cloudant/client/api/ClientBuilder.html#gsonBuilder-com.google.gson.GsonBuilder-) to set a custom `GsonBuilder` which you can register your type adapters on. As per the documentation we will also set our internal adapters on that provided builder.

I think this will meet your needs. There are some limitations, for example, I would not recommend using the `serializeNulls` option (as per #338) because I believe that breaks some of the internal behaviour. Ultimately we intend to use that issue to split the internal GSON from any custom one to avoid that limitation. The further goal for the next major version is to avoid being tied only to GSON (see #352) and allowing a registration point for any object mapper.
