### ISSUE TITLE
SearchResult<T> cannot return result

### ISSUE THREAD

**Issue by Maxim-Gadalov** [cloudant/java-cloudant#368]
Hi, i use cloudant-client 2.9.0, java oracle 1.8.0_141. and spring framework

So i use cloudant search.
When I invoke search with returned type `List<T>` it works nice. but if i want to return `SearchResult<T>` I get an exception:

`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.tracks`

**Lucene query:**  program:("Momentum 2017" OR "IBM")

**Java code:**
_______________________________________________________
```
public List<EventTestModel> search(String selector) {
        return db.search(searchIndexName)
                .includeDocs(true)
                .query(selector, EventTestModel.class);
    }  // this method work nice and return correct data
```
_________________________________________________________
```
public SearchResult<EventTestModel> searchMore(String selector){
            return  db.search(searchIndexName)
                    .querySearchResult(selector, EventTestModel.class);
    } // this code threw an exception marked above
```

The same pieces of code i found on your documentation.

P.S. exception stacktrace:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.tracks
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[gson-2.7.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.7.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.7.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:925) ~[gson-2.7.jar:?]
        at com.cloudant.client.org.lightcouch.internal.CouchDbUtil.jsonToObject(CouchDbUtil.java:86) ~[cloudant-client-2.9.0.jar:?]
        at com.cloudant.client.api.Search.getRows(Search.java:458) ~[cloudant-client-2.9.0.jar:?]
        at com.cloudant.client.api.Search.querySearchResult(Search.java:227) ~[cloudant-client-2.9.0.jar:?]
.
.
.
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at path $.tracks
        at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162) ~[gson-2.7.jar:?]
        at com.google.gson.internal.bind.JsonTreeReader.beginArray(JsonTreeReader.java:71) ~[gson-2.7.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[gson-2.7.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.7.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.7.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.7.jar:?]
        ... 47 more
```

**Comment by tomblench** [comment]
Hi @Maxim-Gadalov, can you provide the definition of `EventTestModel` and a sample document which would match your search criteria?

**Comment by Maxim-Gadalov** [comment]
@tomblench Is it enough for you?
**Example of document:**
```
{
  "_id": "",
  "_rev": "",
  "program": "Bee Healthy",
  "title": "Oftalmólogo - Catalinas",
  "modules": [
    "ENR"
  ],
  "tracks": [
    "All"
  ],
  "topics": [],
  "startDateTime": "2017-08-09T13:00:00Z",
  "endDateTime": "2017-08-09T20:00:00Z",
  "status": "Published",
  "editors": [ ],
  "readers": [],
  "type": "eventcloudantmodel"
}
```
**Search index function:**
```
function (doc) {
  if(doc.program){
    index("program", doc.program, {"store":true});
  }
  if(doc.title){
    index("title", doc.title, {"store":true});
  }
  if(doc.status){
    index("status", doc.status, {"store":true});
  }
  if(doc.startDateTime){
    index("startDateTime", doc.startDateTime, {"store":true});
  }
  if(doc.modules){
    for(var module in doc.modules){
          index("modules", doc.modules[module], {"index":"analyzed","store":true});
    }
  }
  if(doc.tracks){
   for(var track in doc.tracks){
          index("tracks", doc.tracks[track], {"index":"analyzed","store":true});
    }
  }
  if(doc.topics){
    for(var topic in doc.topics){
          index("topics", doc.topics[topic], {"index":"analyzed","store":true});
    }
  }
}
```
![search](https://user-images.githubusercontent.com/22380075/29527675-4f5b241a-86a2-11e7-8898-7f1be53a1bd0.PNG)

**Comment by tomblench** [comment]
@Maxim-Gadalov is it possible for you to share `EventTestModel.java` with us? This will help us understand where the deserialisation is going wrong.

**Comment by Maxim-Gadalov** [comment]
@tomblench , sure.

```
public class EventTestModel extends CloudantModel {

    private String program;
    private String title;
    private List<String> modules;
    private List<String> tracks;
    private List<String> topics;
    private Date startDateTime;
    private Date endDateTime;
    private String status;
    private List<String> editors;
    private List<String> readers;
    private String type;

    public EventTestModel(){

    }

    public EventTestModel(String program, String title, List<String> modules, List<String> tracks, List<String> topics, Date startDateTime, Date endDateTime, String status, List<String> editors, List<String> readers, String type) {
        this.program = program;
        this.title = title;
        this.modules = modules;
        this.tracks = tracks;
        this.topics = topics;
        this.startDateTime = startDateTime;
        this.endDateTime = endDateTime;
        this.status = status;
        this.editors = editors;
        this.readers = readers;
        this.type = type;
    }

    public String getProgram() {
        return program;
    }

    public void setProgram(String program) {
        this.program = program;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<String> getModules() {
        return modules;
    }

    public void setModules(List<String> modules) {
        this.modules = modules;
    }

    public List<String> getTracks() {
        return tracks;
    }

    public void setTracks(List<String> tracks) {
        this.tracks = tracks;
    }

    public List<String> getTopics() {
        return topics;
    }

    public void setTopics(List<String> topics) {
        this.topics = topics;
    }

    public Date getStartDateTime() {
        return startDateTime;
    }

    public void setStartDateTime(Date startDateTime) {
        this.startDateTime = startDateTime;
    }

    public Date getEndDateTime() {
        return endDateTime;
    }

    public void setEndDateTime(Date endDateTime) {
        this.endDateTime = endDateTime;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public List<String> getEditors() {
        return editors;
    }

    public void setEditors(List<String> editors) {
        this.editors = editors;
    }

    public List<String> getReaders() {
        return readers;
    }

    public void setReaders(List<String> readers) {
        this.readers = readers;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;

        EventTestModel that = (EventTestModel) o;

        if (program != null ? !program.equals(that.program) : that.program != null) return false;
        if (title != null ? !title.equals(that.title) : that.title != null) return false;
        if (modules != null ? !modules.equals(that.modules) : that.modules != null) return false;
        if (tracks != null ? !tracks.equals(that.tracks) : that.tracks != null) return false;
        if (topics != null ? !topics.equals(that.topics) : that.topics != null) return false;
        if (startDateTime != null ? !startDateTime.equals(that.startDateTime) : that.startDateTime != null)
            return false;
        if (endDateTime != null ? !endDateTime.equals(that.endDateTime) : that.endDateTime != null) return false;
        if (status != null ? !status.equals(that.status) : that.status != null) return false;
        if (editors != null ? !editors.equals(that.editors) : that.editors != null) return false;
        if (readers != null ? !readers.equals(that.readers) : that.readers != null) return false;
        return type != null ? type.equals(that.type) : that.type == null;
    }

    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + (program != null ? program.hashCode() : 0);
        result = 31 * result + (title != null ? title.hashCode() : 0);
        result = 31 * result + (modules != null ? modules.hashCode() : 0);
        result = 31 * result + (tracks != null ? tracks.hashCode() : 0);
        result = 31 * result + (topics != null ? topics.hashCode() : 0);
        result = 31 * result + (startDateTime != null ? startDateTime.hashCode() : 0);
        result = 31 * result + (endDateTime != null ? endDateTime.hashCode() : 0);
        result = 31 * result + (status != null ? status.hashCode() : 0);
        result = 31 * result + (editors != null ? editors.hashCode() : 0);
        result = 31 * result + (readers != null ? readers.hashCode() : 0);
        result = 31 * result + (type != null ? type.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "EventTestModel{" +
                "program='" + program + '\'' +
                ", title='" + title + '\'' +
                ", modules=" + modules +
                ", tracks=" + tracks +
                ", topics=" + topics +
                ", startDateTime=" + startDateTime +
                ", endDateTime=" + endDateTime +
                ", status='" + status + '\'' +
                ", editors=" + editors +
                ", readers=" + readers +
                ", type='" + type + '\'' +
                '}';
    }
}
```

```
public abstract class CloudantModel extends Model {
	
	@ApiModelProperty(hidden = true)
    @SerializedName("_id")
    private String id;
	
	@ApiModelProperty(hidden = true)
    @SerializedName("_rev")
    private String rev;

    public CloudantModel() {
    }

    public CloudantModel(String id) {
        this.id = id;
    }

    public CloudantModel(String id, String rev) {
        this.id = id;
        this.rev = rev;
    }

    public String getId() {
        return id;
    }

    public CloudantModel setId(String id) {
        this.id = id;
        return this;
    }

    public String getRev() {
        return rev;
    }

    public CloudantModel setRev(String rev) {
        this.rev = rev;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        CloudantModel that = (CloudantModel) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;
        return rev != null ? rev.equals(that.rev) : that.rev == null;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (rev != null ? rev.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return String.format("CloudantModel{id='%s', rev='%s'}",
                id, rev);
    }
}

```

**Comment by tomblench** [comment]
@Maxim-Gadalov we have reproduced your issue.

The problem with searching on fields with arrays is that if the result document only has one entry for that field's array, then it will be returned as a primitive type (eg string), rather than an array of length 1.

You can fix this by registering a custom JSON deserializer:
```java
    private class PrimitiveOrArrayDeserializer implements JsonDeserializer<Collection> {
        public Collection deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context)
                throws JsonParseException {
            if (json.isJsonPrimitive()) {
                JsonArray fakeArray = new JsonArray();
                fakeArray.add(json);
                return context.deserialize(fakeArray, typeOfT);
            } else if (json.isJsonArray()) {
                return context.deserialize(json, typeOfT);
            }
            throw new JsonParseException("Element "+json+" was not an array or a primitive");
        }
    }
```
Note that this is a simple example and you might need more robust handling, eg if this field can be null.

You register this class for each type by using the `JsonAdapter` property. Here I have added this property for all fields which might have length of 1:

```java
    private String program;
    private String title;
    @JsonAdapter(PrimitiveOrArrayDeserializer.class)
    private List<String> modules;
    @JsonAdapter(PrimitiveOrArrayDeserializer.class)
    private List<String> tracks;
    @JsonAdapter(PrimitiveOrArrayDeserializer.class)
    private List<String> topics;
    private Date startDateTime;
    private Date endDateTime;
    private String status;
    @JsonAdapter(PrimitiveOrArrayDeserializer.class)
    private List<String> editors;
    @JsonAdapter(PrimitiveOrArrayDeserializer.class)
    private List<String> readers;
    private String type;
```

Now I can print out the result using your data which I have modified:
```java
        SearchResult<EventTestModel> res = searchMore(db, "program:(\"Bee Healthy\" OR \"IBM\")");
        for (SearchResult.SearchResultRow sr : res.getRows()) {
            System.out.println(sr.getFields());
        }
```
```
EventTestModel{program='Bee Healthy', title='Oftalmólogo - Catalinas', modules=[ENR2, ENR], tracks=[All], topics=null, startDateTime=Wed Aug 09 14:00:00 BST 2017, endDateTime=null, status='Published', editors=null, readers=null, type='null'}
```

**Comment by Maxim-Gadalov** [comment]
@tomblench  thank you for this solution.
But now i have another problem.
For example a have array in document like : 
```
{
...
modules:[
"ENR",
"IBM",
...
],
...
}
```
And if I want to search by modules:"ENR", search result will be only the single line(or array with length 1): `"modules":"ENR"` or `"modules":["ENR"] `

But I want to display all array data. Maybe you can give me advice what I'm doing wrong.

P.S. when I search by another field - result of modules field would be all array data.

**Comment by tomblench** [comment]
@Maxim-Gadalov my colleagues have suggested you should use our Mango (also known as Query) which offers more flexibility when handling data types such as arrays. You can see the documentation [here](https://console.bluemix.net/docs/services/Cloudant/api/cloudant_query.html#query) and a useful tutorial/walkthrough [here](https://developer.ibm.com/dwblog/2015/mango-json-vs-text-indexes/).

Since this is outside of the scope of our Java library, if you have any more questions about Search and Query, you should ask our support team who can be contacted via support@cloudant.com
