### ISSUE TITLE
POST with invokeUpdateHandler?

### ISSUE THREAD

**Issue by srl295** [cloudant/java-cloudant#37]
Is there any way in this API to POST to an update handler? Passing in no docId just results in an error `docId is required` where I would expect it to `POST` instead of `PUT`.
```
java.lang.IllegalArgumentException: docId may not be null.
	at org.lightcouch.internal.CouchDbUtil.assertNotEmpty(Unknown Source)
	at org.lightcouch.CouchDatabaseBase.invokeUpdateHandler(Unknown Source)
	at com.cloudant.client.api.Database.invokeUpdateHandler(Unknown Source)
```

**Comment by srl295** [comment]
I've worked around it with `executeRequest()` so far

**Comment by emlaver** [comment]
A parameter for POST body was added in PR #177 to `invokeUpdateHandler`.  The body is not required and does not need to be passed in.
