### ISSUE TITLE
Database.createIndex does not work for "text" index type

### ISSUE THREAD

**Issue by stephenir** [cloudant/java-cloudant#375]
The createIndex method allows specifying a type, but it doesn't seem like it supports "text" type.

productDb.createIndex(
                "testing",
                "testing",
                "text",
                new IndexField[] { new IndexField("name", IndexField.SortOrder.asc) });

I get the following when I use the code above -

Exception in thread "main" com.cloudant.client.org.lightcouch.CouchDbException: 400 Bad Request at https://stephenrobertson.cloudant.com:443/productdata_dev/_index. Error: invalid_index_fields_definition. Reason: Text Index field definitions must be of the form
            {"name": "non-empty fieldname", "type":
                "boolean,number, or string"}. Def: [{[{<<"name">>,
                                                       <<"asc">>}]}].
	at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:528)
	at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:579)
	at com.cloudant.client.api.Database.createIndex(Database.java:305)
	at com.cloudant.client.api.Database.createIndex(Database.java:288)
	
Using CloudantClient 2.8.0

**Comment by smithsz** [comment]
Thanks for raising this. Unfortunately we don't support the use of text indexes in Cloudant Query. We're using #166 to track this feature enhancement. Apologies for the inconvenience caused.

**Comment by ricellis** [comment]
@stephenir Until the resolution of #166 you should be able to create the index with the other [`createIndex(String indexDefinition)` method](http://static.javadoc.io/com.cloudant/cloudant-client/2.9.0/com/cloudant/client/api/Database.html#createIndex-java.lang.String-) by providing the JSON string of the index definition. Following your example above for a text index named `testing` in a design document called `testing` that is indexing the `name` field of your documents the call would look like:
```java
productDb.createIndex("{\"name\":\"testing\",\"ddoc\":\"testing\",\"type\":\"text\", \"index\":{\"fields\": [{\"name\":\"name\", \"type\":\"string\"}]}}");
```
