### ISSUE TITLE
AllDocsRequestResponse.getDocsAs(Class<D> docType) throws Exception if any of the document was deleted

### ISSUE THREAD

**Issue by andrewnet** [cloudant/java-cloudant#440]
- CloudantClient (java-cloudant) version(s) that are affected by this issue.
  **cloudant-client-2.12.0.jar**
- Java version (including vendor and platform).
  **Any JDK 1.8 (i.e. not JDK related)**
- If you're using the optional okhttp dependency.
  **No (but not related)**
- A small code sample that demonstrates the issue.
  **See below**

### Overview
The AllDocsRequestResponse.getDocsAs(Class<D> docType) works in normal cases. However, if any of the matched documents was deleted in database (it still returned as a match in the result), the method throws Exception. 

### Cause
The **com.cloudant.client.internal.views.RowImpl.getDocumentAsType(Class<D> docType)** shown below only checks if the row has attribute `doc`  and does not handle the case the `doc` attribute has value `null` (in which case, `row.has("doc")` returns true and `row.get("doc")` returns com.google.gson.JsonNull ). For deleted document, this is the case. As the result, the code tries to create object for JsonNull and the exception was thrown.
```
    public <D> D getDocumentAsType(Class<D> docType) {
        D doc = null;
        if(row.has("doc")) {
            doc = gson.fromJson(row.get("doc"), docType);
        }
        return doc;
    }
```
It should be written something like below
```
    public <D> D getDocumentAsType(Class<D> docType) {
        D doc = null;
        if(row.has("doc")) {
            JsonElement element = row.get("doc");
            if (!element.isJsonNull()){
                doc = gson.fromJson(element, docType);
            }
        }
        return doc;
    }
```

### Code sample
```
String[] keys = new String[]{"key1", "key2"};
AllDocsRequest allDocRequest = db.getAllDocsRequestBuilder().includeDocs(true).keys(keys).build();
AllDocsResponse resps = allDocRequest.getResponse();

List<JsonObject> docs = resps.getDocsAs(JsonObject.class);
```

### Exception stack
```
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonNull
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[gson-2.8.0.jar:?]
	at com.cloudant.client.internal.views.RowImpl.getDocumentAsType(RowImpl.java:67) ~[cloudant-client-2.12.0.jar:?]
	at com.cloudant.client.internal.views.ViewResponseImpl.getDocsAs(ViewResponseImpl.java:188) ~[cloudant-client-2.12.0.jar:?]
	at com.cloudant.client.internal.views.AllDocsRequestResponse.getDocsAs(AllDocsRequestResponse.java:67) ~[cloudant-client-2.12.0.jar:?]
	at com.test.MyTask.getAllDocumentsByIds(MyTask.java:112) ~[classes/:?]
	at com.test.MyTask.run(MyTask.java:53) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by tomblench** [comment]
Fixing this under #439 as it's closely related. The best we can do is exclude deleted documents because they can't be serialised to the type the user wants.

**Comment by andrewnet** [comment]
Thanks, @tomblench , couple things though:

**Comment by tomblench** [comment]
Closing as #439 has merged
