### ISSUE TITLE
bulk delete

### ISSUE THREAD

**Issue by tanwald** [cloudant/java-cloudant#444]
If I call the method "bulkDelete" (see below) I get the following error:

> Bad special document member: _deleted.

```java
public List<Response> bulkDelete(List<T> documents) {

        return this.database.bulk(documents
                .stream()
                .map(document -> new CloudantDelete(document.getId(), document.getRev()))
                .collect(Collectors.toList())
        );
    }
```

```java
public class CloudantDelete extends Document {
    private String _deleted = "true";

    public CloudantDelete(String _id, String _rev) {
        this._id = _id;
        this._rev = _rev;
    }
//...
```

- CloudantClient 
2.12.0
- Java version
Oracle JDK 8 
- okhttp dependency.
No

**Comment by smithsz** [comment]
This should work for you:

```java
db.bulk(docs.stream()
        .map(document -> new CloudantDelete(document.getId(), document.getRevision()))
        .collect(Collectors.toList())
);
```

```java
import com.cloudant.client.api.model.Document;
import com.google.gson.annotations.SerializedName;

public class CloudantDelete extends Document {

    @SerializedName("_deleted")
    private Boolean deleted = true;

    public CloudantDelete(String id, String rev) {
        this.setId(id);
        this.setRevision(rev);
    }
}
```
Let me know if you have any further problems.

**Comment by gee4vee** [comment]
This no longer works on newest versions of java-cloudant. I'm seeing this. Is there any way to work around it now?

```
java.lang.IllegalArgumentException: class application.events.CloudantDelete declares multiple JSON fields named _deleted
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.getAdapter(Gson.java:458) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:704) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.toJsonTree(Gson.java:597) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.toJsonTree(Gson.java:576) ~[gson-2.8.5.jar:na]
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.bulk(CouchDatabaseBase.java:279) ~[cloudant-client-2.18.0.jar:na]
```
