### ISSUE TITLE
Cannot connect to IAM only instance on IBM Cloud with VCAP_SERVICES

### ISSUE THREAD

**Issue by a9210** [cloudant/java-cloudant#466]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
Cannot connect to IAM only instance on IBM Cloud with VCAP_SERVICES because VCAP_SERVICES does not contain a credentials.host.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
i.create cloudant instance with only IAM authentication.
ii. connect to the instance with ClientBuilder#bluemix method.
`ClientBuilder.bluemix(System.getenv("VCAP_SERVICES")).build()`

and gets `java.lang.IllegalArgumentException: The Cloudant service instance information was invalid.`

I can connect to that instance with ClientBuilder#url and ClientBuilder#iamApiKey.

### 2. What you expected to happen
Connected to IAM only instance.

### 3. What actually happened
java.lang.IllegalArgumentException: The Cloudant service instance information was invalid.
 at com.cloudant.client.api.ClientBuilder.vcapClientBuilder(ClientBuilder.java:780)
 at com.cloudant.client.api.ClientBuilder.bluemix(ClientBuilder.java:743)
 at com.cloudant.client.api.ClientBuilder.bluemix(ClientBuilder.java:683)
 at com.cloudant.client.api.ClientBuilder.bluemix(ClientBuilder.java:651)

## Environment details
my VCAP_SERVICES
`VCAP_SERVICES:{"cloudantNoSQLDB":[{
  "name": "Cloudant-iam",
  "instance_name": "Cloudant-iam",
  "binding_name": null,
  "credentials": {
    "apikey": "???",
    "iam_apikey_description": "Auto generated apikey during resource-bind operation for Instance - ???",
    "iam_apikey_name": "auto-generated-apikey-???",
    "iam_role_crn": "???::::serviceRole:Manager",
    "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::???",
    "url": "https://???-bluemix.cloudant.com",
    "username": "???-bluemix"
    },
... blah-blah`

Thank you.

**Comment by a9210** [comment]
Thank you , ricellis.

As follow as your instruction, I posted this issue to Cloudant support team.
I'll share the message when I got reply.

**Comment by a9210** [comment]
I've gotten a reply from cloudant support.

> Hello,
> 
> Thankyou for opening this support case.
> The issue you are reporting is a bug on the Cloudant side for which a fix has yet to be implemented.
> 
> Regards,

Thank you ,all.
