### ISSUE TITLE
Couchdb 2.3 unsupported due to clustered "purge_seq" field transition to string value

### ISSUE THREAD

**Issue by sheinbergon** [cloudant/java-cloudant#467]
## Bug Description

Couchdb 2.3 changed the purge_seq field in the `DbInfo` response to be a string (this possibly applies to other sequences as well)

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

Try to configure a client against a CouchDB 2.3 server and issue and query that'll call the  `info()` method from a `Database` instance.

### 2. What you expected to happen

This should have worked

### 3. What actually happened

Gson deserialization failed with the following stacktrace:
```
Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "0-g1AAAAFTeJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFOSA5BMiv___39WIgMedXksQJLhAJACKr2PX22SAshMe4JmJjIkyRNpcQPE4vnEqH0AUUuUuQsgavcT8FACyEP1EDOzADZYXo4"
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:306)
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:296)
	at io.gsonfire.gson.ExcludeByValueTypeAdapterFactory$ExcludeByValueTypeAdapter.read(ExcludeByValueTypeAdapterFactory.java:99)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at io.gsonfire.gson.ExcludeByValueTypeAdapterFactory$ExcludeByValueTypeAdapter.read(ExcludeByValueTypeAdapterFactory.java:99)
	at io.gsonfire.gson.HooksTypeAdapter.deserialize(HooksTypeAdapter.java:86)
	at io.gsonfire.gson.HooksTypeAdapter.read(HooksTypeAdapter.java:54)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:865)
	at com.cloudant.client.org.lightcouch.internal.CouchDbUtil.getResponse(CouchDbUtil.java:229)
	at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:384)
	at com.cloudant.client.api.Database.info(Database.java:1333)
```

## Environment details
- CouchDB versions
   > 2.3
- Version(s) that are affected by this issue.
   > 2.13.1
- Java version including vendor and platform
   > JDK 11 Linux (Azul) , but relevant to all platforms
- Using the optional okhttp dependency.
   > No

**Comment by ricellis** [comment]
Thanks, we are aware of this issue and have plans to resolve it prior to it impacting Cloudant services.

**Comment by sheinbergon** [comment]
@ricellis  thank you for your response. Do you have an estimated timeline to when might this happen?

**Comment by ricellis** [comment]
I'd like it to be in the next release, which I think will be in January.

**Comment by smithsz** [comment]
@sheinbergon The `2.14.0` release includes the fix and is now available from Maven Central.
