### ISSUE TITLE
Query Read TimeOut  Issue  (Its very critical issue in cloudant DB)

### ISSUE THREAD

**Issue by umashanker088** [cloudant/java-cloudant#488]
## Bug Description
Any  query or view query or get post call through API taking more time and throw exception read timeout and  server not responding with time then throw exeception 
we are mentioned 7 sec read timeout in java-cloudant library . 

Suppose that I have 1 Database which is hold 10000000 Documents and build an view on that DB which is emiting whole document.
Query execute through java api's  such as
HA proxy logs 
1.
Jun 26 11:00:09 localhost haproxy[6356]: ****:59287 [26/Jun/2019:11:00:05.453] dbfarm~ dbfarm/****** 4264/0/9/12/4287 200 303 - - ---- 422/422/202/25/0 0/0 {Basic ******} "POST /xyz/_find HTTP/1.1"

2. Jun 26 11:00:28 localhost haproxy[6356]: **********:63037 [26/Jun/2019:11:00:23.982] dbfarm~ dbfarm/*************** 4842/0/39/40/4937 200 329 - - ---- 468/468/239/29/0 0/0 {Basic *******} "GET /XYZ/_design/XYZ/_view/XYZ-view?startkey=%5B%2266666666%22,%22%22%5D&endkey=%5B%228888888888888%22%5D&limit=1&descending=true HTTP/1.1"

### 2. What you expected to happen

How to overcome read timeout and  improve fetching mechanism .   

### 3. What actually happened
 Some time same queries take more time for execution or Less time . 
## Environment details
Cloudant Local Setup version 2.1.0 with 9 node cluster with 2 Active LB with  HAproxy  
- Version(s) that are affected by this issue.
    > 2.9.0
- Java version including vendor and platform
    > 1.8.0_151 OpenJDK Linux
-Using the optional okhttp dependency.
    No

**Comment by emlaver** [comment]
@umashanker088 You can adjust the duration of the client side read timeout with [`ClientBuilder#readTimeout()`](http://static.javadoc.io/com.cloudant/cloudant-client/2.9.0/com/cloudant/client/api/ClientBuilder.html#readTimeout-long-java.util.concurrent.TimeUnit-).  I would recommend that you upgrade your `java-cloudant` version from 2.9.0 to the latest 2.12.0.
If you're still having issues after adjusting the read timeout, please review the best practices for getting support for Cloudant Local: https://pages.github.ibm.com/cloudant/best-practice/local_support.html

**Comment by umashanker088** [comment]
Yes  I have used at client side read timeout attribute in Clientbuilder but we are still getting read timeout exception  in api

**Comment by emlaver** [comment]
@umashanker088 can you provide the Java stacktrace and logging, and can you share your code where this exception is happening?

**Comment by umashanker088** [comment]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
    at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
    at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
    at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:117)
    at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:61)
    at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:92)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:110)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:967)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1107)
    at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:87)
    at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:947)
    at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
    at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316)
    at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88)
    at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1820)
    at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
    at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
    at com.ibm.io.async.AsyncChannelFuture$1.run(AsyncChannelFuture.java:205)
    at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)
Caused by: com.ibm.sbi.lotus.cloudant.common.dto.RestCommonException: com.cloudant.client.org.lightcouch.CouchDbException: Error retrieving server response at https://***************:443/xyx/89916226166.
    at com.ibm.sbi.lotus.cloudant.common.dao.impl.CustomerDaoImpl.modifyCustomer(CustomerDaoImpl.java:145)
    at com.ibm.sbi.lotus.cloudant.common.dao.impl.CustomerDaoImpl$$FastClassBySpringCGLIB$$c1460ee3.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
    at com.ibm.sbi.lotus.cloudant.common.dao.impl.CustomerDaoImpl$$EnhancerBySpringCGLIB$$543f93e5.modifyCustomer(<generated>)
    at com.ibm.sbi.lotus.cloudant.common.service.impl.CustomerServiceImpl.save(CustomerServiceImpl.java:103)
    ... 110 common frames omitted
Caused by: com.cloudant.client.org.lightcouch.CouchDbException: Error retrieving server response at https://***************:443/xyx/89916226166.
    at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:563)
    at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:579)
    at com.cloudant.client.org.lightcouch.CouchDbClient.executeToResponse(CouchDbClient.java:292)
    at com.cloudant.client.org.lightcouch.CouchDbClient.put(CouchDbClient.java:425)
    at com.cloudant.client.org.lightcouch.CouchDbClient.put(CouchDbClient.java:394)
    at com.cloudant.client.org.lightcouch.CouchDatabaseBase.update(CouchDatabaseBase.java:227)
    at com.cloudant.client.api.Database.update(Database.java:837)
    at com.ibm.sbi.lotus.cloudant.common.dao.impl.CustomerDaoImpl.modifyCustomer(CustomerDaoImpl.java:131)
    ... 119 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:127)
    at java.net.SocketInputStream.read(SocketInputStream.java:181)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at com.ibm.jsse2.a.a(a.java:79)
    at com.ibm.jsse2.a.a(a.java:182)
    at com.ibm.jsse2.as.a(as.java:883)
    at com.ibm.jsse2.as.a(as.java:382)
    at com.ibm.jsse2.e.read(e.java:16)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:257)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:297)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:356)
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1584)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:491)
    at com.ibm.net.ssl.www2.protocol.https.b.getResponseCode(b.java:1)
    at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:504)
    ... 126 common frames omitted

**Comment by ricellis** [comment]
A read timeout is generally caused when the server is unable to respond in a timely fashion; i.e. this is more likely a server-side problem than a client-side one. If you make a request to query a view (or index) that hasn't been built yet then that request will cause it to be built (assuming you are not allowing stale results). If that index building takes a longer than the configured read timeout then the client will experience a read timeout because the server is unable to respond until the view is built. We can't help with that type of data modelling and index optimization problem here, you would need to talk to your Cloudant Local support.

When this problem is occurring are you able to run the same queries using `curl` (or similar tooling) without experiencing the slow down? That will at least narrow down if the problem is server-side.

>we are mentioned 7 sec read timeout in java-cloudant library .

The default read timeout is 5 minutes.

>Yes I have used at client side read timeout attribute in Clientbuilder but we are still getting read timeout exception in api

If you have configured the read timeout, then it will be whatever value you have set it to; is 7 seconds what you chose?

>Any query or view query or get post call through API taking more time and throw exception read timeout

The stack trace you have posted is for a document update, so it looks like this problem may not be limited to querying.

>Jun 26 11:00:09 localhost haproxy[6356]: :59287 [26/Jun/2019:11:00:05.453] dbfarm~ dbfarm/\*\* 4264/0/9/12/4287 200 303 - - ---- 422/422/202/25/0 0/0 {Basic \*\*} "POST /xyz/_find HTTP/1.1"
>
>Jun 26 11:00:28 localhost haproxy[6356]: :63037 [26/Jun/2019:11:00:23.982] dbfarm~ dbfarm/\*\* 4842/0/39/40/4937 200 329 - - ---- 468/468/239/29/0 0/0 {Basic \*\*} "GET /XYZ/_design/XYZ/_view/XYZ-view?startkey=%5B%2266666666%22,%22%22%5D&endkey=%5B%228888888888888%22%5D&limit=1&descending=true HTTP/1.1"

These HAProxy log lines do not appear to correspond to read timeouts as they do not have abnormal client termination states. The wait for the client to send the request does appear to be long though (>4 seconds). Have you investigated your JVM performance - perhaps you are suffering long GC pauses or some other contention?

**Comment by umashanker088** [comment]
Ok I will check db logs and as well as communicate with cloudant SME.

Can you provide some parameters from HA proxy logs to measurement  performance

**Comment by ricellis** [comment]
Read the [HAProxy manual](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#8.2.3)
The numbers `4264/0/9/12/4287` are field 6 `TR '/' Tw '/' Tc '/' Tr '/' Ta*`

>"TR" is the total time in milliseconds spent waiting for a full HTTP
    request from the client (not counting body) after the first byte was
    received. It can be "-1" if the connection was aborted before a complete
    request could be received or the a bad request was received. It should
    always be very small because a request generally fits in one single packet.
    Large times here generally indicate network issues between the client and
    haproxy or requests being typed by hand. See section 8.4 "Timing Events"
    for more details.

This is outside the scope of java-cloudant though, here's the link for [Cloudant Local support](https://cloud.ibm.com/docs/services/Cloudant?topic=cloudant-ibm-cloudant-local-support)
