### ISSUE TITLE
Connection Timeout while trying to connect cloudant via VM

### ISSUE THREAD

**Issue by veduboy** [cloudant/java-cloudant#489]
#214 Bug Description
2019-08-13 17:43:35.059 ERROR 50017 --- [           main] c.c.h.i.interceptors.CookieInterceptor   : Failed to read cookie response

java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_161]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_161]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_161]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
        at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_161]
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
        at sun.net.NetworkClient.doConnect(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) ~[na:1.8.0_161]
        at com.cloudant.http.HttpConnection.execute(HttpConnection.java:313) [cloudant-http-2.13.1.jar!/:na]
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.requestCookie(CookieInterceptorBase.java:169) [cloudant-http-2.13.1.jar!/:na]
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.requestCookie(CookieInterceptorBase.java:198) [cloudant-http-2.13.1.jar!/:na]
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.interceptRequest(CookieInterceptorBase.java:74) [cloudant-http-2.13.1.jar!/:na]
        at com.cloudant.http.HttpConnection.execute(HttpConnection.java:290) [cloudant-http-2.13.1.jar!/:na]
        at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:535) [cloudant-client-2.13.1.jar!/:na]
        at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:629) [cloudant-client-2.13.1.jar!/:na]
        at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:372) [cloudant-client-2.13.1.jar!/:na]
        at com.cloudant.client.org.lightcouch.CouchDbClient.getAllDbs(CouchDbClient.java:226) [cloudant-client-2.13.1.jar!/:na]
        at com.cloudant.client.api.CloudantClient.getAllDbs(CloudantClient.java:269) [cloudant-client-2.13.1.jar!/:na]
        at com.example.demo.CloudantTestApplication.main(CloudantTestApplication.java:35) [classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_161]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [cloudantTest-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [cloudantTest-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [cloudantTest-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [cloudantTest-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: com.cloudant.client.org.lightcouch.CouchDbException: 401 Unauthorized at https://f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com:443/_all_dbs. Error: unauthorized. Reason: one of _all_dbs, _admin, server_admin is required for this request.
        at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:578)
        at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:629)
        at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:372)
        at com.cloudant.client.org.lightcouch.CouchDbClient.getAllDbs(CouchDbClient.java:226)
        at com.cloudant.client.api.CloudantClient.getAllDbs(CloudantClient.java:269)
        at com.example.demo.CloudantTestApplication.main(CloudantTestApplication.java:35)
        ... 8 more

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

  CloudantClient client = ClientBuilder.url(new URL(
                                    "https:/*****************************.cloudant.com"))
                                    .username("***************************")
                                 .password("*****************************")
                                    .build();
            List<String> dbs=client.getAllDbs();
            System.out.println("all dbs :\t"+dbs);
### 2. What you expected to happen
connection created and response with all the database created in cloud 
## Environment details
- Version(s) that are affected by this issue.
     =2.13.1
- Java version including vendor and platform
    > 1.8.0_151 OpenJDK rhel
- Using the optional okhttp dependency.
    > Yes|No

**Comment by ricellis** [comment]
From your stack trace:
>Caused by: com.cloudant.client.org.lightcouch.CouchDbException: 401 Unauthorized at https://f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com:443/_all_dbs. **Error: unauthorized. Reason: one of _all_dbs, _admin, server_admin is required for this request.**

The credentials you are using do not have permission to list `_all_dbs`. This is not a java-cloudant error.

**Comment by veduboy** [comment]
I still get the error before I tried with

CloudantClient client = ClientBuilder.url(new URL(
"https:/.cloudant.com"))
.username("")
.proxyURL(new URL("************"))
.password("***************************")
.build();

when I try the below code  
CloudantClient client = ClientBuilder.url(new URL(
"https:/.cloudant.com"))
.username("")
.password("***************************")
.build();

I till get the error 



2019-08-13 19:01:07.731 ERROR 50785 --- [           main] c.c.h.i.interceptors.CookieInterceptor   : Failed to read cookie response
2019-08-13 19:11:17.139 ERROR 50915 --- [           main] c.c.h.i.interceptors.CookieInterceptor   : Failed to read cookie response

java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_161]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_161]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_161]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
        at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_161]
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
        at sun.net.NetworkClient.doConnect(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[na:1.8.0_161]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) ~[na:1.8.0_161]
        at com.cloudant.http.HttpConnection.execute(HttpConnection.java:313) [cloudant-http-2.13.1.jar!/:na]
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.requestCookie(CookieInterceptorBase.java:169) [cloudant-http-2.13.1.jar!/:na]
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.requestCookie(CookieInterceptorBase.java:198) [cloudant-http-2.13.1.jar!/:na]
        at com.cloudant.http.internal.interceptors.CookieInterceptorBase.interceptRequest(CookieInterceptorBase.java:74) [cloudant-http-2.13.1.jar!/:na]
        at com.cloudant.http.HttpConnection.execute(HttpConnection.java:290) [cloudant-http-2.13.1.jar!/:na]
        at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:535) [cloudant-client-2.13.1.jar!/:na]
        at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:629) [cloudant-client-2.13.1.jar!/:na]
        at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:372) [cloudant-client-2.13.1.jar!/:na]
        at com.cloudant.client.org.lightcouch.CouchDbClient.getAllDbs(CouchDbClient.java:226) [cloudant-client-2.13.1.jar!/:na]
        at com.cloudant.client.api.CloudantClient.getAllDbs(CloudantClient.java:269) [cloudant-client-2.13.1.jar!/:na]
        at com.example.demo.CloudantTestApplication.main(CloudantTestApplication.java:35) [classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_161]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [cloudantTest-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [cloudantTest-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [cloudantTest-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [cloudantTest-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]

**Comment by ricellis** [comment]
Can you `curl https://f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com/` successfully from the VM?

Are you using a proxy or not?

What type of credentials are you trying to use: Cloudant username and password, Cloudant legacy API key or IAM API key?

**Comment by veduboy** [comment]
Yes I can curl successfully from VM

First when I had open ticket I am using proxy code , where authorization issue occurred , thanks for correcting me..

Second I execute code without proxy then I got error which I had updated in the comments

**Comment by veduboy** [comment]
And type of credentials are username and password

**Comment by ricellis** [comment]
Please try this simpler version and see if you still get a `Connection timed out`.
Note querying the `serverVersion` does not require any credentials, use this code as-is assuming the account name is from your stack trace is the correct one.

```java
CloudantClient client = ClientBuilder
  .account("f55176da-7aba-4a9a-aece-d38651420cf4-bluemix")
  .build();
System.out.println(client.serverVersion());
```

**Comment by veduboy** [comment]
Tried the same code get 
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: com.cloudant.client.org.lightcouch.CouchDbException: Error retrieving server response at https://f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com:443.
        at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:613)
        at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:629)
        at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:372)
        at com.cloudant.client.org.lightcouch.CouchDbClient.metaInformation(CouchDbClient.java:251)
        at com.cloudant.client.org.lightcouch.CouchDbClient.serverVersion(CouchDbClient.java:242)
        at com.cloudant.client.api.CloudantClient.serverVersion(CloudantClient.java:281)
        at com.example.demo.CloudantTestApplication.main(CloudantTestApplication.java:22)
        ... 8 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
        at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:554)
        ... 14 more

### **while execute the same code in windows machine get OUTPUT--> 2.1.1**

**Comment by veduboy** [comment]
quick question :
what port has been used curl while calling url?
and while we are calling from java program it might have used different port

**Comment by ricellis** [comment]
>what port has been used curl while calling url?

You can `curl -v` to confirm, but it will be `443` as that is the default for `https` protocol.

The other difference between `curl` and Java is that `curl` may use http2 by default, whereas Java 8 (almost certainly) won't, but it shouldn't make a difference. You can `curl -v --http1.1 https://f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com/` if you want to check that HTTP 1.1 also works.

So just to be clear what we've identified so far is:
* there is no issue connecting directly from your windows machine
* connections from a VM running on the same windows machine (or somewhere else?) are timing out
* `curl`ing the Cloudant account endpoint from the VM works normally

Initially I would suspect a problem with the VMs network configuration, but if `curl` is working it seems like the network configuration problem is isolated to the JVM running in the VM. Are you able to make any other HTTP requests out from that JVM?

**Comment by veduboy** [comment]
Your identification is correct so far.
Q---> Are you able to make any other HTTP requests out from that JVM?
No able to check, As the VM is prohibited for connection with Internet except the URL of "cloudant https://f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com/"

**Comment by veduboy** [comment]
and while using 
curl -v --http1.1 https://f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com/
curl: option --http1.1: is unknown

curl -v https://f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com/ --http1.1
curl: option --http1.1: is unknown

I am novice on networking , Is this mean cloudant URL is not being supported by http1.1  or JVM way

**Comment by ricellis** [comment]
>Is this mean cloudant URL is not being supported by http1.1

No, it just means your curl version is older than 7.33.0 when they added the `--http1.1` option (and http2 support I think). Your curl is almost certainly using `http/1.1` then anyway - the verbose output should tell you what http version it was using anyway.

>the VM is prohibited for connection with Internet except the URL of "cloudant

Oh. That seems a likely place for trouble - I guess it depends how that filtering is managed? Do you think the addition of the port in the URL might break it - i.e. can you successfully connect to 443 directly e.g. `curl -v https://f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com:443`

In any case, it does seem likely that this isn't a java-cloudant problem though, given that java-cloudant works correctly for the same account from your Windows machine.

**Comment by veduboy** [comment]
**curl -v https://f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com:443 working fine** 

* About to connect() to proxy 10.137.20.33 port 8080 (#0)
*   Trying 10.137.20.33...
* Connected to 10.137.20.33 (10.137.20.33) port 8080 (#0)
* Establish HTTP proxy tunnel to f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com:443
> CONNECT f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com:443 HTTP/1.1
> Host: f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.cloudant.com,O="Cloudant, LLC.",L=Boston,ST=Massachusetts,C=US
*       start date: Jan 21 00:00:00 2019 GMT
*       expire date: Apr 09 12:00:00 2021 GMT
*       common name: *.cloudant.com
*       issuer: CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: f55176da-7aba-4a9a-aece-d38651420cf4-bluemix.cloudant.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: must-revalidate
< Content-Length: 219
< Content-Type: application/json
< Date: Wed, 14 Aug 2019 13:20:08 GMT
< Server: CouchDB/2.1.1 (Erlang OTP/20)
< X-Couch-Request-ID: ff9b27afd4
< X-Frame-Options: DENY
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
< X-Cloudant-Request-Class: unlimited
< X-Cloudant-Backend: bm-cc-us-south-14
< Via: 1.1 lb1.bm-cc-us-south-14 (Glum/1.82.0)
<
{"couchdb":"Welcome","version":"2.1.1","vendor":{"name":"IBM Cloudant","version":"8076","variant":"paas"},"features":["geo","iam","partitioned","pluggable-storage-engines","scheduler"],"features_flags":["partitioned"]}
* Connection #0 to host **.***.**.** left intact

**while while I append use same url in java code it still timeout** 

Question : If the curl able to connect to 443 by default (it means the port is available to connect) how come the JVM not (just asking to know)

 **Yes it seed this isn't a java-cloudant problem specific**

**Comment by ricellis** [comment]
OK so it looks like you do have a proxy in play - I guess a system proxy on the VM. You could try configuring the JVM with `-Djava.net.useSystemProxies=true`.

**Comment by veduboy** [comment]
-Djava.net.useSystemProxies=true i have applied on application.property ? just confirming
and 

need to provide .proxyURL(new URL("")) as below

CloudantClient client = ClientBuilder.url(new URL(
"https:/.cloudant.com"))
.username("")
**.proxyURL(new URL(""))**
.password("***************")
.build();

**Comment by ricellis** [comment]
>-Djava.net.useSystemProxies=true i have applied on application.property

I don't know what `application.property` is - some Spring thing?
I would expect it to be a system property like:
`java -Djava.net.useSystemProxies=true -jar yourapp.jar`
I don't know the incantation for system properties in Spring.

>need to provide .proxyURL(new URL("")) as below

No, if you use the `useSystemProxies` property you should not need to configure the `proxyURL` (doing so would set an explicit proxy bypassing whatever the system default is - I would only go down that route if you can't get the system property to work because by doing so you'd end up hard-coding some IP address or something).

**Comment by veduboy** [comment]
perfect that on my demo application, I will do same changes on other and let you know thanks
