### ISSUE TITLE
Deleting docs in bulk regression

### ISSUE THREAD

**Issue by gee4vee** [cloudant/java-cloudant#497]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
The issue was addressed here:
https://github.com/cloudant/java-cloudant/issues/444

It no longer works in newest versions of cloudant-java:

```
java.lang.IllegalArgumentException: class application.events.CloudantDelete declares multiple JSON fields named _deleted
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.getAdapter(Gson.java:458) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[gson-2.8.5.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:704) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.toJsonTree(Gson.java:597) ~[gson-2.8.5.jar:na]
	at com.google.gson.Gson.toJsonTree(Gson.java:576) ~[gson-2.8.5.jar:na]
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.bulk(CouchDatabaseBase.java:279) ~[cloudant-client-2.18.0.jar:na]
	at com.cloudant.client.api.Database.bulk(Database.java:1184) ~[cloudant-client-2.18.0.jar:na]
```

### 2. What you expected to happen
Documents are deleted

### 3. What actually happened
An exception is thrown

## Environment details
- Version(s) that are affected by this issue.
    > 2.18.0
- Java version including vendor and platform
    > 1.8.0_181, vendor: Oracle Corporation, macOS
- Using the optional okhttp dependency.
    > No

**Comment by emlaver** [comment]
@gee4vee can you provide the code you are using to execute the bulk docs request with _deleted flag? Also, do you have a class that looks exactly like one below?
```
import com.cloudant.client.api.model.Document;
import com.google.gson.annotations.SerializedName;

public class CloudantDelete extends Document {

    @SerializedName("_deleted")
    private Boolean deleted = true;

    public CloudantDelete(String id, String rev) {
        this.setId(id);
        this.setRevision(rev);
    }
}
```

**Comment by emlaver** [comment]
Never-mind my comment above.  The `_deleted` flag was added to `Document` class in 2.13.0.

If you are using this code below:
```
db.bulk(docs.stream()
        .map(document -> new CloudantDelete(document.getId(), document.getRevision()))
        .collect(Collectors.toList())
);
```
You can now set the deleted flag to true in the constructor:
```
public class CloudantDelete extends Document {

    @SerializedName("_deleted")
    private Boolean deleted = true;

    public CloudantDelete(String id, String rev) {
        this.setId(id);
        this.setRevision(rev);
        this.setDeleted(true);
    }
}
```

**Comment by ricellis** [comment]
As per the [release notes for 2.13.0](https://github.com/cloudant/java-cloudant/releases/tag/2.13.0)

>The suggested work-around is to remove this [`deleted`] field from classes which sub-class Document.

I've corrected the above example to reflect this, but the `CloudantDelete` subclass approach was a workaround for the fact that the `deleted` flag was not included in the `Document` class. I think in the case of this example a `CloudantDelete` class is no longer required at all as since 2.13.0 it is possible to set the `deleted` field on `Document`.

If you already have a list of `Document` then you can just do this:
```java
for (Document d : docs) {
  d.setDeleted(true);
}
db.bulk(docs)
```

If you have some map of ids and revs you can for example map them straight to `Document` instead of creating a `CloudantDelete` subclass e.g.
```java
db.bulk(
    idsToRevs.entrySet().stream().map(doc -> {
        Document d = new Document();
        d.setId(doc.getKey());
        d.setRevision(doc.getValue());
        d.setDeleted(true);
        return d;
    }).collect(Collectors.toList()));
```

**Comment by gee4vee** [comment]
Using `setDeleted` and removing the `deleted` field worked. Thanks!
