### ISSUE TITLE
Caused By: javax.net.ssl.SSLHandshakeException: General SSLEngine problem

### ISSUE THREAD

**Issue by wrushasendakhane** [cloudant/java-cloudant#505]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
com.cloudant.client.org.lightcouch.CouchDbException: Error retrieving server response at https://042490fb-545c-4fff-b953-adac51178bf4-bluemix.cloudant.com:443.
	at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:632)
	at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:648)
	at com.cloudant.client.org.lightcouch.CouchDbClient.get(CouchDbClient.java:389)
	at com.cloudant.client.org.lightcouch.CouchDbClient.metaInformation(CouchDbClient.java:268)
	at com.cloudant.client.org.lightcouch.CouchDbClient.serverVersion(CouchDbClient.java:259)
	Truncated. see log file for complete stacktrace
Caused By: java.io.IOException: Failed to read server response from  https://042490fb-545c-4fff-b953-adac51178bf4-bluemix.cloudant.com:443/_session
	at com.cloudant.http.internal.interceptors.CookieInterceptorBase.wrapIOException(CookieInterceptorBase.java:257)
	at com.cloudant.http.internal.interceptors.CookieInterceptorBase.makeSessionRequest(CookieInterceptorBase.java:157)
	at com.cloudant.http.internal.interceptors.CookieInterceptorBase.requestCookie(CookieInterceptorBase.java:100)
	at com.cloudant.http.internal.interceptors.CookieInterceptorBase.interceptRequest(CookieInterceptorBase.java:169)
	at com.cloudant.http.HttpConnection.execute(HttpConnection.java:291)
	Truncated. see log file for complete stacktrace
Caused By: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528)
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1197)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1165)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469)
	Truncated. see log file for complete stacktrace
Caused By: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1709)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	Truncated. see log file for complete stacktrace
Caused By: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
	Truncated. see log file for complete stacktrace
Caused By: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	Truncated. see log file for complete stacktrace
>

**Comment by ricellis** [comment]
>Caused By: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

As you can see from the stack trace the problem here is that you don't have a valid certification path. The root certificate needed for Cloudant servers is available in the default trust store. Given you are seeing this error it is likely that the trust store you are using does not include the necessary certificate.

This is not a java-cloudant problem.
