### ISSUE TITLE
Fetching docs from cloudant using java-cloudant APIs

### ISSUE THREAD

**Issue by Everly-Okorji** [cloudant/java-cloudant#60]
I tried calling db.view("_all_docs").includeDocs(true).query(JSONObject.class) on my code but I'm getting weird errors about Gson, and it raised an exception:
java.lang.IllegalArgumentException: Invalid type of value. Type: [com.google.gson.internal.LinkedTreeMap] with value: [my_json_but_with_all_quotes_stripped]

When I called the function with Object.class instead of JSONObject.class, I got an Object which, when printed, looks almost like JSON but with all of the quotes stripped out (even for strings with whitespace). 

When I called the function with String.class, I got some error along the lines of "Expected STRING but found BEGIN_OBJECT".

**Comment by ricellis** [comment]
@Everly-Okorji which JSON object class are you trying to use? com.google.gson.JsonObject or org.json.JSONObject or something else?

**Comment by ricellis** [comment]
It would also be helpful if you could provide the complete stack trace from the exception, thanks.

**Comment by Everly-Okorji** [comment]
com.ibm.json.java.JSONObject. And here's a stack trace: 

[ERROR   ] An unhandled exception occurred which will be propagated to the container.
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.json.java.JSONObject.put:241'
java.lang.IllegalArgumentException: Invalid type of value.  Type: [com.google.gson.internal.LinkedTreeMap] with value: [{cellPhone={}, legalName=[{lastName=Doe, givenNameOne=John, prefix=Mr}], gender=m, birthDate=01/01/1991, homePhone={}, primaryResidenceAddress=[{addressLineTwo=Apt 1, provinceState=Texas, zipPostalCode=78705, addressLineOne=123 Abc Ave, city=Austin, country=United States}]}]
	at com.ibm.json.java.JSONObject.put(JSONObject.java:241)
	at [internal classes]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:188)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:868)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at org.lightcouch.View.query(Unknown Source)
	at com.cloudant.client.api.View.query(Unknown Source)
	at com.ibm.mdm.cps.backend.CloudantAccess.getAllEntities(CloudantAccess.java:89)
	at com.ibm.mdm.cps.objects.ResourceHelper.fetchAll(ResourceHelper.java:56)
	at com.ibm.mdm.cps.services.PersonResource.getAll(PersonResource.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.wink.server.internal.handlers.InvokeMethodHandler.handleRequest(InvokeMethodHandler.java:63)
	at org.apache.wink.server.handlers.AbstractHandler.handleRequest(AbstractHandler.java:33)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.CreateInvocationParametersHandler.handleRequest(CreateInvocationParametersHandler.java:54)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleSubResourceMethod(FindResourceMethodHandler.java:188)
	at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleRequest(FindResourceMethodHandler.java:110)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.FindRootResourceHandler.handleRequest(FindRootResourceHandler.java:95)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.HeadMethodHandler.handleRequest(HeadMethodHandler.java:53)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.OptionsMethodWADLHandler.handleRequest(OptionsMethodWADLHandler.java:51)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.SearchResultHandler.handleRequest(SearchResultHandler.java:33)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.log.ResourceInvocation.handleRequest(ResourceInvocation.java:92)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.log.Requests.handleRequest(Requests.java:76)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.handlers.AbstractHandlersChain.run(AbstractHandlersChain.java:60)
	at org.apache.wink.server.internal.RequestProcessor.handleRequestWithoutFaultBarrier(RequestProcessor.java:207)
	at org.apache.wink.server.internal.RequestProcessor.handleRequest(RequestProcessor.java:154)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:106)
	at [internal classes]

[ERROR   ] SRVE0315E: An exception occurred: com.ibm.ws.webcontainer.webapp.WebAppErrorReport: java.lang.IllegalArgumentException: Invalid type of value.  Type: [com.google.gson.internal.LinkedTreeMap] with value: [{cellPhone={}, legalName=[{lastName=Doe, givenNameOne=John, prefix=Mr}], gender=m, birthDate=01/01/1991, homePhone={}, primaryResidenceAddress=[{addressLineTwo=Apt 1, provinceState=Texas, zipPostalCode=78705, addressLineOne=123 Abc Ave, city=Austin, country=United States}]}]
	at com.ibm.json.java.JSONObject.put(JSONObject.java:241)
	at [internal classes]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:188)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:868)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at org.lightcouch.View.query(Unknown Source)
	at com.cloudant.client.api.View.query(Unknown Source)
	at com.ibm.mdm.cps.backend.CloudantAccess.getAllEntities(CloudantAccess.java:89)
	at com.ibm.mdm.cps.objects.ResourceHelper.fetchAll(ResourceHelper.java:56)
	at com.ibm.mdm.cps.services.PersonResource.getAll(PersonResource.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.wink.server.internal.handlers.InvokeMethodHandler.handleRequest(InvokeMethodHandler.java:63)
	at org.apache.wink.server.handlers.AbstractHandler.handleRequest(AbstractHandler.java:33)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.CreateInvocationParametersHandler.handleRequest(CreateInvocationParametersHandler.java:54)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleSubResourceMethod(FindResourceMethodHandler.java:188)
	at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleRequest(FindResourceMethodHandler.java:110)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.FindRootResourceHandler.handleRequest(FindRootResourceHandler.java:95)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.HeadMethodHandler.handleRequest(HeadMethodHandler.java:53)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.OptionsMethodWADLHandler.handleRequest(OptionsMethodWADLHandler.java:51)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.handlers.SearchResultHandler.handleRequest(SearchResultHandler.java:33)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.log.ResourceInvocation.handleRequest(ResourceInvocation.java:92)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.internal.log.Requests.handleRequest(Requests.java:76)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
	at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
	at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)
	at org.apache.wink.server.handlers.AbstractHandlersChain.run(AbstractHandlersChain.java:60)
	at org.apache.wink.server.internal.RequestProcessor.handleRequestWithoutFaultBarrier(RequestProcessor.java:207)
	at org.apache.wink.server.internal.RequestProcessor.handleRequest(RequestProcessor.java:154)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:106)
	at [internal classes]
Caused by: java.lang.IllegalArgumentException: Invalid type of value.  Type: [com.google.gson.internal.LinkedTreeMap] with value: [{cellPhone={}, legalName=[{lastName=Doe, givenNameOne=John, prefix=Mr}], gender=m, birthDate=01/01/1991, homePhone={}, primaryResidenceAddress=[{addressLineTwo=Apt 1, provinceState=Texas, zipPostalCode=78705, addressLineOne=123 Abc Ave, city=Austin, country=United States}]}]

**Comment by mariobriggs** [comment]
Any particular reason u are using 'com.ibm.json.java.JSONObject'. If not i would suggest to move off it

**Comment by Everly-Okorji** [comment]
Yes. It's the approved version for my work.

**Comment by mariobriggs** [comment]
does the problem stated go away if you query for 'com.google.gson.JsonObject.class' ? If it does, you should move to it. As to approved version, here how i spin it - obviously you are approved for java-cloudant (coz u are using it) and thus the latter' explicit dependencies are approved too

**Comment by Everly-Okorji** [comment]
I'm not sure how this relates to the issue at hand. The code should work irrespective of the JSONObject implementation, and it doesn't. I'm reporting this as an issue, even though I've already reverted my code to use another REST implementation for fetching docs from clouding. 

I'm sure Java-cloudant works with some other implementation but that's not what I'm asking here. Thanks for your comment but it's not helpful in my case.

**Comment by brhaible** [comment]
Have you tried to use the methods GsonBuilder.registerTypeAdapter or GsonBuilder.registerTypeAdapterFactory, in order to specify how the CloudantClient object should proceed with the conversion to your desired JSONObject class?

**Comment by Everly-Okorji** [comment]
My app was supposed to be pretty basic, and so the amount of work required relative to my code is pretty high. Thanks for the suggestion though!

I'll go ahead and mark this as solved because I found a workaround that works temporarily.
